// stubs/presets/primevue/auth/resources/js/Pages/Auth/TwoFactorChallenge.vue
<script setup>
import { Head, router, useForm } from '@inertiajs/vue3';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import AuthCard from '@/Components/AuthCard.vue';
import FormError from '@/Components/FormError.vue';
import { useLanguage } from '@/lib/i18n';

const form = useForm({
    code: '',
    recovery_code: '',
});

const { t } = useLanguage();

const submitCode = () => {
    form.recovery_code = '';
    form.post(route('two-factor.verify'));
};

const submitRecovery = () => {
    form.code = '';
    form.post(route('two-factor.verify'));
};

const cancelChallenge = () => router.delete(route('two-factor.cancel'));
</script>

<template>
    <Head :title="t('twoFactorChallengeTitle')" />

    <AuthCard :title="t('twoFactorTitle')" :subtitle="t('twoFactorSubtitle')" :tab="t('twoFactorTab')">
        <form class="space-y-4" @submit.prevent="submitCode">
            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('authCode') }}</label>
                <InputText v-model="form.code" class="w-full tracking-[0.3em]" autofocus inputmode="numeric" />
                <FormError :message="form.errors.code" />
            </div>
            <Button type="submit" :label="t('verifyCode')" icon="pi pi-shield" class="w-full" :loading="form.processing" />
        </form>

        <div class="my-6 h-px bg-white/10" />

        <form class="space-y-4" @submit.prevent="submitRecovery">
            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('recoveryCode') }}</label>
                <InputText v-model="form.recovery_code" class="w-full uppercase" />
                <FormError :message="form.errors.recovery_code" />
            </div>
            <Button type="submit" :label="t('useRecovery')" icon="pi pi-key" severity="secondary" outlined class="w-full" :loading="form.processing" />
        </form>

        <Button :label="t('backToLogin')" icon="pi pi-arrow-left" severity="secondary" text class="mt-5 w-full" @click="cancelChallenge" />
    </AuthCard>
</template>

// stubs/presets/react/auth/resources/js/Pages/Auth/TwoFactorChallenge.jsx
import { Head, router, useForm } from '@inertiajs/react';
import { ArrowLeft, KeyRound, Shield } from 'lucide-react';
import FormError from '@/Components/FormError';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import AuthLayout from '@/Layouts/AuthLayout';
import { useLanguage } from '@/lib/i18n';

export default function TwoFactorChallenge() {
    const { t } = useLanguage();
    const codeForm = useForm({ code: '' });
    const recoveryForm = useForm({ recovery_code: '' });

    const submitCode = (event) => {
        event.preventDefault();
        codeForm.post(route('two-factor.verify'));
    };

    const submitRecovery = (event) => {
        event.preventDefault();
        recoveryForm.post(route('two-factor.verify'));
    };

    return (
        <AuthLayout title={t('twoFactorTitle')} subtitle={t('twoFactorSubtitle')} tab={t('twoFactorTab')}>
            <Head title={t('twoFactorTitle')} />
            <form className="space-y-4" onSubmit={submitCode}>
                <div>
                    <Label htmlFor="code">{t('authCode')}</Label>
                    <Input id="code" value={codeForm.data.code} onChange={(e) => codeForm.setData('code', e.target.value)} className="tracking-[0.3em]" autoFocus inputMode="numeric" />
                    <FormError message={codeForm.errors.code} />
                </div>
                <Button type="submit" block disabled={codeForm.processing}>
                    <Shield size={17} />
                    {t('verifyCode')}
                </Button>
            </form>

            <div className="my-6 h-px bg-white/10" />

            <form className="space-y-4" onSubmit={submitRecovery}>
                <div>
                    <Label htmlFor="recovery_code">{t('recoveryCode')}</Label>
                    <Input id="recovery_code" value={recoveryForm.data.recovery_code} onChange={(e) => recoveryForm.setData('recovery_code', e.target.value)} className="uppercase" />
                    <FormError message={recoveryForm.errors.recovery_code || recoveryForm.errors.code} />
                </div>
                <Button type="submit" block variant="secondary" disabled={recoveryForm.processing}>
                    <KeyRound size={17} />
                    {t('useRecovery')}
                </Button>
            </form>

            <Button type="button" block variant="ghost" className="mt-5" onClick={() => router.delete(route('two-factor.cancel'))}>
                <ArrowLeft size={17} />
                {t('backToLogin')}
            </Button>
        </AuthLayout>
    );
}
