// stubs/presets/react/auth/resources/js/Pages/Auth/ConfirmPassword.jsx
import { Head, useForm } from '@inertiajs/react';
import { Shield } from 'lucide-react';
import FormError from '@/Components/FormError';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import AuthLayout from '@/Layouts/AuthLayout';
import { useLanguage } from '@/lib/i18n';

export default function ConfirmPassword() {
    const { t } = useLanguage();
    const form = useForm({ password: '' });

    const submit = (event) => {
        event.preventDefault();
        form.post(route('password.confirm.store'));
    };

    return (
        <AuthLayout title={t('confirmPasswordTitle')} subtitle={t('confirmPasswordSubtitle')} tab={t('confirmPasswordTab')}>
            <Head title={t('confirmPasswordTitle')} />
            <form className="space-y-5" onSubmit={submit}>
                <div>
                    <Label htmlFor="password">{t('password')}</Label>
                    <Input id="password" type="password" value={form.data.password} onChange={(e) => form.setData('password', e.target.value)} autoFocus autoComplete="current-password" />
                    <FormError message={form.errors.password} />
                </div>
                <Button type="submit" block disabled={form.processing}>
                    <Shield size={17} />
                    {t('confirm')}
                </Button>
            </form>
        </AuthLayout>
    );
}

// stubs/resources/js/Pages/Auth/ConfirmPassword.vue
<script setup>
import { Head, useForm } from '@inertiajs/vue3';
import Button from 'primevue/button';
import Password from 'primevue/password';
import AuthCard from '@/Components/AuthCard.vue';
import FormError from '@/Components/FormError.vue';

const form = useForm({ password: '' });
</script>

<template>
    <Head title="Confirmar contraseña" />

    <AuthCard title="Confirmar contraseña" subtitle="Confirma tu contraseña para continuar con esta acción sensible.">
        <form class="space-y-5" @submit.prevent="form.post(route('password.confirm.store'))">
            <div>
                <label class="mb-2 block text-sm font-semibold">Contraseña</label>
                <Password v-model="form.password" class="w-full" input-class="w-full" :feedback="false" toggle-mask autofocus autocomplete="current-password" />
                <FormError :message="form.errors.password" />
            </div>

            <Button type="submit" label="Confirmar" icon="pi pi-shield" class="w-full" :loading="form.processing" />
        </form>
    </AuthCard>
</template>
