// stubs/presets/react/auth/resources/js/Pages/Auth/VerifyEmail.jsx
import { Head, router } from '@inertiajs/react';
import { LogOut, Mail } from 'lucide-react';
import StatusMessage from '@/Components/StatusMessage';
import { Button } from '@/Components/ui/button';
import AuthLayout from '@/Layouts/AuthLayout';
import { useLanguage } from '@/lib/i18n';

export default function VerifyEmail({ status }) {
    const { t } = useLanguage();

    return (
        <AuthLayout title={t('verifyEmailTitle')} subtitle={t('verifyEmailSubtitle')} tab={t('verifyEmailTab')}>
            <Head title={t('verifyEmailTitle')} />
            <StatusMessage message={status === 'verification-link-sent' ? t('verificationSent') : ''} />
            <div className="flex flex-col gap-3">
                <Button type="button" onClick={() => router.post(route('verification.send'))}>
                    <Mail size={17} />
                    {t('resendVerification')}
                </Button>
                <Button type="button" variant="secondary" onClick={() => router.post(route('logout'))}>
                    <LogOut size={17} />
                    {t('logout')}
                </Button>
            </div>
        </AuthLayout>
    );
}

// stubs/resources/js/Pages/Auth/VerifyEmail.vue
<script setup>
import { Head, router } from '@inertiajs/vue3';
import Button from 'primevue/button';
import AuthCard from '@/Components/AuthCard.vue';
import StatusMessage from '@/Components/StatusMessage.vue';

defineProps({ status: String });
</script>

<template>
    <Head title="Verifica tu email" />

    <AuthCard title="Verifica tu email" subtitle="Antes de continuar, confirma tu dirección con el enlace que enviamos.">
        <StatusMessage v-if="status === 'verification-link-sent'" message="Enviamos un nuevo enlace de verificación." />

        <div class="flex flex-col gap-3">
            <Button label="Reenviar verificación" icon="pi pi-envelope" @click="router.post(route('verification.send'))" />
            <Button label="Cerrar sesión" icon="pi pi-sign-out" severity="secondary" outlined @click="router.post(route('logout'))" />
        </div>
    </AuthCard>
</template>
