// stubs/presets/react/auth/resources/js/Pages/Auth/Register.jsx
import { Head, Link, useForm } from '@inertiajs/react';
import { UserPlus } from 'lucide-react';
import FormError from '@/Components/FormError';
import { Button } from '@/Components/ui/button';
import { Input } from '@/Components/ui/input';
import { Label } from '@/Components/ui/label';
import AuthLayout from '@/Layouts/AuthLayout';
import { useLanguage } from '@/lib/i18n';

export default function Register() {
    const { t } = useLanguage();
    const form = useForm({ name: '', email: '', password: '', password_confirmation: '' });

    const submit = (event) => {
        event.preventDefault();
        form.post(route('register'), {
            onFinish: () => form.reset('password', 'password_confirmation'),
        });
    };

    return (
        <AuthLayout title={t('register')} subtitle={t('registerSubtitle')} tab={t('registerTab')}>
            <Head title={t('register')} />
            <form className="space-y-5" onSubmit={submit}>
                <div>
                    <Label htmlFor="name">{t('name')}</Label>
                    <Input id="name" value={form.data.name} onChange={(e) => form.setData('name', e.target.value)} autoComplete="name" autoFocus />
                    <FormError message={form.errors.name} />
                </div>
                <div>
                    <Label htmlFor="email">{t('email')}</Label>
                    <Input id="email" value={form.data.email} onChange={(e) => form.setData('email', e.target.value)} autoComplete="username" />
                    <FormError message={form.errors.email} />
                </div>
                <div>
                    <Label htmlFor="password">{t('password')}</Label>
                    <Input id="password" type="password" value={form.data.password} onChange={(e) => form.setData('password', e.target.value)} autoComplete="new-password" />
                    <FormError message={form.errors.password} />
                </div>
                <div>
                    <Label htmlFor="password_confirmation">{t('confirmPassword')}</Label>
                    <Input id="password_confirmation" type="password" value={form.data.password_confirmation} onChange={(e) => form.setData('password_confirmation', e.target.value)} autoComplete="new-password" />
                    <FormError message={form.errors.password_confirmation} />
                </div>
                <Button type="submit" block disabled={form.processing}>
                    <UserPlus size={17} />
                    {t('register')}
                </Button>
            </form>
            <p className="mt-6 text-center text-sm text-slate-400">
                {t('alreadyAccount')} <Link href={route('login')} className="kit-link">{t('login')}</Link>
            </p>
        </AuthLayout>
    );
}

// stubs/presets/primevue/auth/resources/js/Pages/Auth/Register.vue
<script setup>
import { Head, Link, useForm } from '@inertiajs/vue3';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Password from 'primevue/password';
import AuthCard from '@/Components/AuthCard.vue';
import FormError from '@/Components/FormError.vue';
import { useLanguage } from '@/lib/i18n';

const form = useForm({
    name: '',
    email: '',
    password: '',
    password_confirmation: '',
});

const { t } = useLanguage();

const submit = () => {
    form.post(route('register'), {
        onFinish: () => form.reset('password', 'password_confirmation'),
    });
};
</script>

<template>
    <Head :title="t('register')" />

    <AuthCard :title="t('register')" :subtitle="t('registerSubtitle')" :tab="t('registerTab')">
        <form class="space-y-5" @submit.prevent="submit">
            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('name') }}</label>
                <InputText v-model="form.name" class="w-full" autocomplete="name" autofocus />
                <FormError :message="form.errors.name" />
            </div>

            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('email') }}</label>
                <InputText v-model="form.email" type="email" class="w-full" autocomplete="username" />
                <FormError :message="form.errors.email" />
            </div>

            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('password') }}</label>
                <Password v-model="form.password" class="w-full" input-class="w-full" toggle-mask autocomplete="new-password" />
                <FormError :message="form.errors.password" />
            </div>

            <div>
                <label class="mb-2 block text-sm font-semibold">{{ t('confirmPassword') }}</label>
                <Password v-model="form.password_confirmation" class="w-full" input-class="w-full" :feedback="false" toggle-mask autocomplete="new-password" />
                <FormError :message="form.errors.password_confirmation" />
            </div>

            <Button type="submit" :label="t('register')" icon="pi pi-user-plus" class="w-full" :loading="form.processing" />
        </form>

        <p class="mt-6 text-center text-sm text-slate-400">
            {{ t('alreadyAccount') }}
            <Link :href="route('login')" class="font-semibold text-cyan-200 hover:text-cyan-100">{{ t('login') }}</Link>
        </p>
    </AuthCard>
</template>
