// stubs/presets/react/install/resources/js/Components/LanguageSwitcher.jsx
import { Languages } from 'lucide-react';
import { Button } from '@/Components/ui/button';
import { useLanguage } from '@/lib/i18n';

export default function LanguageSwitcher() {
    const { locale, setLocale, t } = useLanguage();

    return (
        <div className="flex items-center gap-1" aria-label={t('language')}>
            <Languages size={16} className="text-slate-400" />
            <Button
                type="button"
                variant={locale === 'es' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setLocale('es')}
            >
                ES
            </Button>
            <Button
                type="button"
                variant={locale === 'en' ? 'default' : 'ghost'}
                size="sm"
                onClick={() => setLocale('en')}
            >
                EN
            </Button>
        </div>
    );
}

// stubs/presets/naive/install/resources/js/Components/LanguageSwitcher.vue
<script setup>
import { Languages } from '@lucide/vue';
import { NButton } from 'naive-ui';
import { useLanguage } from '@/lib/i18n';

const { locale, setLocale, t } = useLanguage();
</script>

<template>
    <div class="flex items-center gap-1" :aria-label="t('language')">
        <Languages :size="16" class="text-slate-400" />
        <NButton size="small" :type="locale === 'es' ? 'primary' : 'default'" :quaternary="locale !== 'es'" @click="setLocale('es')">ES</NButton>
        <NButton size="small" :type="locale === 'en' ? 'primary' : 'default'" :quaternary="locale !== 'en'" @click="setLocale('en')">EN</NButton>
    </div>
</template>
