// stubs/presets/react/auth/resources/js/Pages/Auth/VerifyEmail.jsx
import { Head, router } from '@inertiajs/react';
import { LogOut, Mail } from 'lucide-react';
import StatusMessage from '@/Components/StatusMessage';
import { Button } from '@/Components/ui/button';
import AuthLayout from '@/Layouts/AuthLayout';
import { useLanguage } from '@/lib/i18n';

export default function VerifyEmail({ status }) {
    const { t } = useLanguage();

    return (
        <AuthLayout title={t('verifyEmailTitle')} subtitle={t('verifyEmailSubtitle')} tab={t('verifyEmailTab')}>
            <Head title={t('verifyEmailTitle')} />
            <StatusMessage message={status === 'verification-link-sent' ? t('verificationSent') : ''} />
            <div className="flex flex-col gap-3">
                <Button type="button" onClick={() => router.post(route('verification.send'))}>
                    <Mail size={17} />
                    {t('resendVerification')}
                </Button>
                <Button type="button" variant="secondary" onClick={() => router.post(route('logout'))}>
                    <LogOut size={17} />
                    {t('logout')}
                </Button>
            </div>
        </AuthLayout>
    );
}

// stubs/presets/naive/auth/resources/js/Pages/Auth/VerifyEmail.vue
<script setup>
import { Head, router } from '@inertiajs/vue3';
import { LogOut, Mail } from '@lucide/vue';
import { NButton } from 'naive-ui';
import AuthCard from '@/Components/AuthCard.vue';
import StatusMessage from '@/Components/StatusMessage.vue';
import { useLanguage } from '@/lib/i18n';

defineProps({ status: String });
const { t } = useLanguage();
</script>

<template>
    <Head :title="t('verifyEmailTitle')" />

    <AuthCard :title="t('verifyEmailTitle')" :subtitle="t('verifyEmailSubtitle')" :tab="t('verifyEmailTab')">
        <StatusMessage v-if="status === 'verification-link-sent'" :message="t('verificationSent')" />

        <div class="flex flex-col gap-3">
            <NButton type="primary" @click="router.post(route('verification.send'))">
                <template #icon><Mail :size="17" /></template>
                {{ t('resendVerification') }}
            </NButton>
            <NButton secondary @click="router.post(route('logout'))">
                <template #icon><LogOut :size="17" /></template>
                {{ t('logout') }}
            </NButton>
        </div>
    </AuthCard>
</template>
